FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt ./requirements.txt

RUN apt-get update && apt-get install -y --no-install-recommends \
        ca-certificates \
        netbase \
        build-essential \
        libblas-dev \
        liblapack-dev \
        libfreetype6-dev \
        python-dev-is-python3 \
        python3-tk \
        && rm -rf /var/lib/apt/lists/*

RUN pip3 install -r requirements.txt

EXPOSE 8501

COPY . .

ENTRYPOINT ["streamlit", "run"]

CMD ["streamlit_app.py"]