[theme]
primaryColor="#203a6b" 
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#2c4f92"
textColor="#111111"
font="sans serif"

[client]
showSidebarNavigation = false

[server]
enableStaticServing = true