[theme]
primaryColor="#203a6b" 
secondaryColor="2c4f92"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#111111"
font="sans serif"

[client]
showSidebarNavigation = false

[server]
enableStaticServing = true